# Generated by Django 3.2.3 on 2021-05-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.TextField(default=1622202691.360322),
        ),
    ]
