# Generated by Django 3.2.3 on 2021-05-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20210531_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='created_at',
            field=models.TextField(default=1622444621.46485),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1622444621.46485),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.TextField(default=1622444621.46485),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='created_at',
            field=models.TextField(default=1622444621.46485),
        ),
    ]
