# Generated by Django 3.2.3 on 2021-05-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210525_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.TextField(default=1622178801.198095),
        ),
    ]
